[package]
name = "mod_synth"
version = "0.1.0"
edition = "2021"
cpal = "0.13"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13"
instant = "0.1.12"
wasi = "0.11.0+wasi-snapshot-preview1"
wasmparser = "0.102.0"
parity-wasm = "0.45.0"
cranelift-wasm = "0.94.0"
wasmtime-environ = "7.0.0"
wasmtime-runtime = "7.0.0"
wasmi = "0.29.0"
wasmer = "3.1.1"
wasmtime-jit = "7.0.0"
wasmtime-cranelift = "7.0.0"
serde-wasm-bindgen = "0.5.0"
wasmer-compiler-cranelift = "3.1.1"
wasmer-engine-universal = "2.3.0"
wasmer-wasi = "3.1.1"
console_log = "1.0.0"
yew-macro = "0.20.0"
downcast-rs = "1.2.0"
